[package]
name = "core-test-2"
version.workspace = true
authors.workspace = true
license.workspace = true
edition.workspace = true
description = "Core test 2"

[dependencies]
core-test-1.workspace = true
